// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools 2015 v1.7.160
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IgnoreFiles
{
    static class Vsix
    {
        public const string Id = "7ac24965-ea21-4108-9cac-6e46394aaaef";
        public const string Name = ".ignore";
        public const string Description = "A lanuage service for dealing with all types of .ignore files such as .gitignore, .tfignore etc.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "git, tfs, ignore";
    }
}
